defaults: &defaults
  base_url: "http://www.worldcat.org/webservices/catalog/search/worldcat/opensearch?count=3&wskey="
  loaded_link: "https://umaryland.on.worldcat.org/search?queryString="
  url_link: "https://umaryland.on.worldcat.org/search?queryString=no%3A+"
  wskey: ""

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
